spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: >-
                    -Xmx1500m
                    -Dvertx.cacheDirBase=/tmp/vertx
